name: AdvancedChat
main: net.advancedplugins.chat.Core
version: @version@
api-version: 1.17

# Load before these plugins for tab completion
loadbefore:
  - Essentials
  - EssentialsX
  - CMI

libraries:
  - org.openjdk.nashorn:nashorn-core:15.3
softdepend:
  - Vault
  - SuperVanish
  - PlaceholderAPI
  - ProtocolLib
  - DiscordSRV
  - TownyChat
permissions:
  advancedchat.ignorejoinformat.*:
    description: Allows players to ignore join messages.
    default: false
  advancedchat.ignorequitformat.*:
    description: Allows players to ignore quit messages.
    default: false
  advancedchat.chat.talk:
    description: Allows players to talk in chat.
    default: true
  advancedchat.chat.mention.allow:
    description: Allows players to be mentioned in chat.
    default: true
  advancedchat.chat.mention.use:
    description: Allows players to use mentions in chat.
    default: true
  advancedchat.chat.colors:
    description: Grants access to use colored text in chat messages.
    default: op
  advancedchat.chat.magic:
    description: Grants access to use 'magic' formatting (obfuscated text) in chat.
    default: op
  advancedchat.use:
    description: General permission for using AdvancedChat features.
    default: op
  advancedchat.channels:
    description: Grants access to chat channels features.
    default: op
  advancedchat.admin.command.ignore.all:
    description: Admin permission to ignore all players.
    default: op
  advancedchat.admin.command.ignore.player:
    description: Admin permission to ignore a specific player.
    default: op
  advancedchat.admin.command.unignore.all:
    description: Admin permission to stop ignoring all players.
    default: op
  advancedchat.admin.command.unignore.player:
    description: Admin permission to stop ignoring a specific player.
    default: op

