blank_issues_enabled: false
contact_links:
  - name: "Get in touch with our support team"
    url: "https://discord.gg/advancedplugins"
    about: "Need help using AdvancedChat? Join our Discord Server for help!"
